// Auth
export const FETCH_ME = 'FETCH_ME';
export const LOCATION_SUCCESS = 'LOCATION_SUCCESS';
export const SIGN_IN = 'SIGN_IN';
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_FAIL = 'SIGN_UP_FAIL';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';
export const UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
export const UPDATE_ACCOUNT_SUCCESS = 'UPDATE_ACCOUNT_SUCCESS';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_VERIFY = 'RESET_PASSWORD_VERIFY';
export const RESET_PASSWORD_SAVE = 'RESET_PASSWORD_SAVE';
export const SET_COMPANY_FEATURES = 'SET_COMPANY_FEATURES';
export const SET_COMPANY_FEATURES_SUCCESS = 'SET_COMPANY_FEATURES_SUCCESS';

// Feature
export const FETCH_FEATURES = 'FETCH_FEATURES';
export const FETCH_FEATURES_SUCCESS = 'FETCH_FEATURES_SUCCESS';
export const FETCH_FEATURES_FAIL = 'FETCH_FEATURES_FAIL';

// Firm
export const FETCH_FIRMS_SUCCESS = 'FETCH_FIRMS_SUCCESS';

// Legal 
export const FETCH_LEGAL_USER_TERMS = 'FETCH_LEGAL';
export const FETCH_LEGAL_USER_PRIVACY = 'FETCH_LEGAL';
export const FETCH_LEGAL_BUISNESS_TERMS = 'FETCH_LEGAL';
export const FETCH_LEGAL_BUSINESS_PRIVACY = 'FETCH_LEGAL';
export const FETCH_LEGAL_SUCCESS = 'FETCH_LEGAL_SUCCESS';
export const FETCH_LEGAL_FAIL = 'FETCH_LEGAL_FAIL';

// FirmReport
export const FETCH_CURRENT_FIRM_REPORT = 'FETCH_CURRENT_FIRM_REPORT';
export const FETCH_CURRENT_FIRM_REPORT_SUCCESS = 'FETCH_CURRENT_FIRM_REPORT_SUCCESS';
export const FETCH_CURRENT_FIRM_REPORT_FAIL = 'FETCH_CURRENT_FIRM_REPORT_FAIL';
export const FETCH_FIRM_REPORTS = 'FETCH_FIRM_REPORTS';
export const FETCH_FIRM_REPORTS_SUCCESS = 'FETCH_FIRM_REPORTS_SUCCESS';
export const FETCH_FIRM_REPORTS_FAIL = 'FETCH_FIRM_REPORTS_FAIL';

// Holiday
export const FETCH_HOLIDAYS = 'FETCH_HOLIDAYS';
export const FETCH_HOLIDAYS_SUCCESS = 'FETCH_HOLIDAYS_SUCCESS';
export const FETCH_HOLIDAYS_FAIL = 'FETCH_HOLIDAYS_FAIL';

// Offer
export const FETCH_OFFERS_SUCCESS = 'FETCH_OFFERS_SUCCESS';

// Payment
export const FETCH_PAYMENTS = 'FETCH_PAYMENTS';
export const FETCH_PAYMENTS_SUCCESS = 'FETCH_PAYMENTS_SUCCESS';
export const FETCH_PAYMENTS_FAIL = 'FETCH_PAYMENTS_FAIL';
export const SEND_PAYMENTS = 'SEND_PAYMENTS';
export const FETCH_CARD_DETAILS = 'FETCH_CARD_DETAILS';
export const FETCH_CARD_DETAILS_SUCCESS = 'FETCH_CARD_DETAILS_SUCCESS';
export const FETCH_CARD_DETAILS_FAIL = 'FETCH_CARD_DETAILS_FAIL';
export const SEND_STRIPE_TOKEN = 'SEND_STRIPE_TOKEN';
export const SEND_STRIPE_TOKEN_SUCCESS = 'SEND_STRIPE_TOKEN_SUCCESS';
export const SEND_STRIPE_TOKEN_FAIL = 'SEND_STRIPE_TOKEN_FAIL';

// Pin
export const FETCH_MY_PINS = 'FETCH_MY_PINS';
export const FETCH_MY_PINS_SUCCESS = 'FETCH_MY_PINS_SUCCESS';
export const FETCH_MY_PINS_FAIL = 'FETCH_MY_PINS_FAIL';
export const VIEW_PIN = 'VIEW_PIN';
export const VIEW_PIN_SUCCESS = 'VIEW_PIN_SUCCESS';
export const DELETE_PIN = 'DELETE_PIN';
export const DELETE_PIN_SUCCESS = 'DELETE_PIN_SUCCESS';
export const ACTIVATE_PIN = 'ACTIVATE_PIN';
export const BUY_PIN = 'BUY_PIN';
export const FETCH_NEAREST_PINS = 'FETCH_NEAREST_PINS';
export const FETCH_NEAREST_PINS_SUCCESS = 'FETCH_NEAREST_PINS_SUCCESS';
export const FETCH_NEAREST_PINS_FAIL = 'FETCH_NEAREST_PINS_FAIL';
export const VISIT_PIN = 'VISIT_PIN';

// PinCatalog
export const FETCH_PIN_CATALOGS = 'FETCH_PIN_CATALOGS';
export const FETCH_PIN_CATALOGS_SUCCESS = 'FETCH_PIN_CATALOGS_SUCCESS';
export const FETCH_PIN_CATALOGS_FAIL = 'FETCH_PIN_CATALOGS_FAIL';
export const VIEW_PIN_CATALOG = 'VIEW_PIN_CATALOG';
export const VIEW_PIN_CATALOG_SUCCESS = 'VIEW_PIN_CATALOG_SUCCESS';

// Post
export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAIL = 'FETCH_POSTS_FAIL';
export const FETCH_MY_POSTS = 'FETCH_MY_POSTS';
export const FETCH_MY_POSTS_SUCCESS = 'FETCH_MY_POSTS_SUCCESS';
export const FETCH_MY_POSTS_FAIL = 'FETCH_MY_POSTS_FAIL';
export const SEARCH_POSTS = 'SEARCH_POSTS';
export const SEARCH_POSTS_SUCCESS = 'SEARCH_POSTS_SUCCESS';
export const SEARCH_POSTS_FAIL = 'SEARCH_POSTS_FAIL';
export const CREATE_POST = 'CREATE_POST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const EDIT_POST = 'EDIT_POST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
export const VIEW_POST = 'VIEW_POST';
export const VIEW_POST_SUCCESS = 'VIEW_POST_SUCCESS';
export const PREVIEW_POST = 'PREVIEW_POST';
export const PREVIEW_POST_FAIL = 'PREVIEW_POST_FAIL';
export const PREVIEW_POST_SUCCESS = 'PREVIEW_POST_SUCCESS';
export const SWIPE_POST = 'SWIPE_POST';
export const LIKE_POST = 'LIKE_POST';
export const LIKE_POST_SUCCESS = 'LIKE_POST_SUCCESS';
export const DISLIKE_POST = 'DISLIKE_POST';
export const DISLIKE_POST_SUCCESS = 'DISLIKE_POST_SUCCESS';
export const UNFAVORITE_POST = 'UNFAVORITE_POST';
export const UNFAVORITE_POST_SUCCESS = 'UNFAVORITE_POST_SUCCESS';
export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const FETCH_LIKED_POSTS = 'FETCH_LIKED_POSTS';
export const FETCH_LIKED_POSTS_SUCCESS = 'FETCH_LIKED_POSTS_SUCCESS';
export const FETCH_LIKED_POSTS_FAIL = 'FETCH_LIKED_POSTS_FAIL';
export const SET_EDITING_POST_FIELD = 'SET_EDITING_POST_FIELD';
export const SET_EDITING_POST = 'SET_EDITING_POST';

// Report
export const CREATE_REPORT = 'CREATE_REPORT';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const CREATE_REPORT_FAIL = 'CREATE_REPORT_FAIL';
export const SET_REPORT_FIELD = 'SET_REPORT_FIELD';

// Schedule
export const FETCH_SCHEDULES_SUCCESS = 'FETCH_SCHEDULES_SUCCESS';

// SupportTicket
export const CREATE_SUPPORT_TICKET = 'CREATE_SUPPORT_TICKET';

// Clear Post
export const CLEAR_EDITING_POST = 'CLEAR_EDITING_POST';
