import { StyleSheet, Platform } from "react-native";
import {
  width,
  verticalScale,
  moderateScale,
  scale,
} from "../../Utils/scaling";
const IS_IOS = Platform.OS === "ios";
export const likedIconSize = verticalScale(25);
const styles = StyleSheet.create({
  headerContainer: {
    position: "absolute",
    width: "100%",
    height: verticalScale(70),
    backgroundColor: "transparent",
    borderBottomWidth: 0,
    top: 0,
    left: 0,
    zIndex: 1000,
    flexDirection: "row",
    justifyContent: "space-between",
  },
  blurHeaderWrapper: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: verticalScale(70),
    overflow: "hidden",
  },
  blurHeader: {
    position: "absolute",
    top: 0,
    left: 0,
    width: "100%",
    height: verticalScale(70),
  },
  heartButton: {
    marginRight: scale(10),
    alignSelf: "center",
  },
  content: {
    flex: 1,
  },
  adImageContainer: {
    position: "relative",
    top: 0,
    left: 0,
    width: width,
    height: verticalScale(252),
    justifyContent: "flex-end",
    alignItems: "flex-end",
  },
  adImage: {
    // flex: 1,
    width: width,
    height: verticalScale(252),
    position: "absolute",
    bottom: 0,
    left: 0,
    // alignSelf: 'flex-end',
    // top: verticalScale(-200),
    // bottom: verticalScale(200),
  },

  branchActionsContainer: {
    position: "absolute",
    top: verticalScale(-60), // verticalScale(190),
    backgroundColor: "transparent",
    height: verticalScale(128),
    zIndex: 2,
    paddingHorizontal: scale(30),
    width: "100%",
    flexDirection: "row",
    justifyContent: "space-between",
    elevation: 1,
  },
  //   branchActions: {
  //     marginHorizontal: scale(30),
  //     height: '100%',
  //     backgroundColor: 'transparent',
  //     flexDirection: 'row',
  //     justifyContent: 'space-between',
  //   },
  actionButton: {
    width: verticalScale(40),
    height: verticalScale(40),
    paddingTop: 0,
    paddingBottom: 0,
    borderRadius: verticalScale(40) / 2,
    borderWidth: verticalScale(4),
    borderColor: "white",
    justifyContent: "center",
    alignItems: "center",
    alignSelf: "center",
    elevation: 0,
    // position: 'relative',
  },
  rearActions: {
    // position: 'relative',
    justifyContent: "center",
  },
  middleActions: {
    alignItems: "center",
  },
  branchLogo: {
    width: verticalScale(100),
    height: verticalScale(100),
  },
  branchText: {
    fontSize: moderateScale(18),
    fontWeight: "bold",
    width: 250,
    textAlign: 'center',
    color: "#6E6969",
  },
  shareButton: {
    position: "absolute",
    bottom: verticalScale(5),
    alignItems: "flex-end",
  },
  branchInfo: {
    // height: verticalScale(186),
    backgroundColor: "white",
    marginHorizontal: scale(10),
    marginBottom: verticalScale(15),
    paddingTop: verticalScale(90),
    paddingHorizontal: scale(25),
    paddingBottom: verticalScale(25),
    borderBottomLeftRadius: verticalScale(20),
    borderBottomRightRadius: verticalScale(20),
    borderTopWidth: 0,
    borderWidth: 1,
    borderColor: "#ddd",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.16,
    shadowRadius: 6,
    elevation: 1,
    flexDirection: "column",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  features: {
    flexDirection: "row",
    width: "100%",
    justifyContent: "space-around",
  },
  featureIconsContainer: {
    width: scale(15),
    height: verticalScale(15),
    justifyContent: "center",
    alignItems: "center",
  },
  featureIcons: {
    flex: 1,
    resizeMode: "contain",
  },
  firstLine: {
    marginTop: verticalScale(9),
    fontSize: moderateScale(12),
    color: "#6E6969",
  },
  secondLine: {
    marginTop: verticalScale(7),
    fontSize: moderateScale(12),
    color: "#9B9797",
  },
  thirdLine: {
    marginTop: verticalScale(13),
    fontSize: moderateScale(12),
    color: "#4B4747",
    fontWeight: "bold",
  },
  extendedGroup: {
    marginTop: verticalScale(15),
    flexDirection: "row",
    alignItems: "center",
  },
  extendedButton: {
    // height: verticalScale(20),
    width: "50%",
    justifyContent: "center",
  },
  extendedText: {
    fontSize: moderateScale(12),
  },
  verticalDivider: {
    height: verticalScale(20),
    width: 0,
    borderWidth: 0.5,
    borderColor: "#9B9797",
  },
});

export default styles;
